# import = ["~/.config/alacritty/themes/coolnight.toml"]

# [env]
# TERM = "xterm-256color"

# [shell]
# program = "zsh"
# args    = ["-c", "~/.config/tmux/tmux_chooser.sh"]

[window]
padding.x    = 10
padding.y    = 10
# opacity      = 0.9
decorations  = "Buttonless"
startup_mode = "Maximized"

[font]
normal.family = "Iosevka Nerd Font"

#regular
size = 15

#for video
# size = 35.0
