# By BBQ191

colors.draw_bold_text_with_bright_colors= true

  # Default colors
[colors.primary]
    background=        '#011627'
    foreground=        '#acb4c2'
    bright_foreground= '#eeeeee'

  # Cursor colors
[colors.cursor]
    text=   '#080808'
    cursor= '#9ca1aa'

  # Selection colors
  [colors.selection]
    text=       '#080808'
    background= '#b2ceee'

  # Normal colors

[colors.normal]
    black=   '#1d3b53'
    red=     '#fc514e'
    green=   '#a1cd5e'
    yellow=  '#e3d18a'
    blue=    '#82aaff'
    magenta= '#c792ea'
    cyan=    '#7fdbca'
    white=   '#a1aab8'

  # Bright colors
[colors.bright]
    black=   '#7c8f8f'
    red=     '#ff5874'
    green=   '#21c7a8'
    yellow=  '#ecc48d'
    blue=    '#82aaff'
    magenta= '#ae81ff'
    cyan=    '#7fdbca'
    white=   '#d6deeb'


# [colors.primary]
# background = '#011423'
# foreground = '#CBE0F0'
#
# # Colors the cursor will use if `custom_cursor_colors` is true
# [colors.cursor]
# text   = "#011423"
# cursor = "#47FF9C"
#
# [colors.normal]
# black   = "#022D51"
# red     = "#E52E2E"
# green   = "#44FFB1"
# yellow  = "#FFE073"
# blue    = "#0FC5ED"
# magenta = "#a277ff"
# cyan    = "#24EAF7"
# white   = "#24EAF7"
#
# [colors.bright]
# black   = "#143652"
# red     = "#E52E2E"
# green   = "#44FFB1"
# yellow  = "#FFE073"
# blue    = "#A277FF"
# magenta = "#a277ff"
# cyan    = "#24EAF7"
# white   = "#24EAF7"
